// This file is auto-generated by scripts/git_version.py.
// Please do not edit manually.
#pragma once

#ifndef PROJECT_VER
#define PROJECT_VER "v1.2.1-alpha.8-dev"
#endif

static const char PROJECT_VER_STR[] = "v1.2.1-alpha.8-dev";
